### PR TITLE
Update test.txt

### PR DESCRIPTION
**Pull request by fish9167**

### CODE REVIEW

**Comment by fish0607** [comment]
@cocos-robot

**Comment by fish0607** [comment]
@cocos-robot

**Comment by fish0607** [comment]
fdsgsgsgagag

**Comment by fish9167** [comment]
@cocos-robot

**Comment by fish9167** [comment]
@cocos-robot run test cases

**Comment by fish0607** [comment]
@cocso-robot run test cases

**Comment by fish0607** [comment]
@cocso-robot run test cases

**Pull request merged**
